# Generated by Django 4.0 on 2021-12-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketbooker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='type',
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.IntegerField(default=0, verbose_name='ticket price'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='code',
            field=models.CharField(default=0, max_length=12),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=50, verbose_name='event name'),
        ),
    ]
